### ISSUE TITLE
feature request - support enum value accessors

### ISSUE THREAD

**Issue by happy-barney** [tobyink/p5-type-tiny#109]
Example (pseudocode)
```
declare Foo, as Enum[qw[ foo bar baz ]];

# usage:
Foo->foo;
Foo->bar;
```

in case Enum values are not identifier:
```
declare Foo, as Enum( { foo => 1, bar => 2,  baz => 3 } ];
```

idea for backward compatibility - enable methods only if first entry of Enum is a hashref (probably allowing mixed - when it is not empty, only those values in hashref will be usable as methods
```
declare Foo, as Enum[ {}, qw[ foo bar baz ] ];
```

**Comment by tobyink** [comment]
It's an interesting idea, but I prefer something like:

```perl
use Type::Tiny::Enum Foo => qw( foo bar baz );

...
has foo_status => (
  is => 'ro',
  isa => Foo,
);

...

if ( $self->foo_status eq FOO_BAZ ) {
  ...;
}
```

So `use Type::Tiny::Enum Foo => qw( foo bar baz )` would import a **Foo** type constraint, plus constants `FOO_FOO`, `FOO_BAR`, and `FOO_BAZ`.

Constants are fast, and if you misspell one of them, it will blow up at compile time. `Foo->bazz` would only blow up at run time.

**Comment by happy-barney** [comment]
this is not bad idea as well, but that will not work for anonymous enums

for later example, maybe even ?
```
if ($self->foo_status->is_baz)
```

**Comment by happy-barney** [comment]
anyway, I have no strict requirement for syntax, I just would like to have some automation for propagating enum values into symbols

**Comment by tobyink** [comment]
If you use MooX::Enumeration or MooseX::Enumeration, you can do:

```perl
has foo_status => (
  is => 'ro',
  isa => Foo,
  handles => 1,
);

...

if ( $self->is_baz ) {
  ...;
}
```

Or:

```perl
has foo_status => (
  is => 'ro',
  isa => Foo,
  handles => 2,
);

...

if ( $self->foo_status_is_baz ) {
  ...;
}
```

**Comment by happy-barney** [comment]
hm, true, this is not related to `Type::Tiny`

**Comment by tobyink** [comment]
Again, I've split this out into a couple of enhancements I think are practical and useful.

**Comment by tobyink** [comment]
FYI, in the [latest dev release](https://metacpan.org/release/TOBYINK/Type-Tiny-1.999_003), if a type library contains enum types, then you can do:

```perl
use My::Types -constants;
```

And you'll get constants exported for each value of the enum, so you can do:

```perl
has foo_status => (
  is => 'ro',
  isa => Foo,
);

...

if ( $self->foo_status eq FOO_BAZ ) {
  ...;
}
```

Additionally, it supports:

```perl
use Type::Tiny::Enum Foo => qw( foo bar baz );
```

You can similarly define Type::Tiny::{Class,Duck,Role} type constraints like:

```perl
use Type::Tiny::Class 'HTTP::Tiny';

if ( is_HTTPTiny( $object ) ) {
  ...;
}
else {
  $object = HTTPTiny->new;
}

use Type::Tiny::Role 'Throwable';

if ( is_Throwable( $e ) ) {
  ...;
}

use Type::Tiny::Duck 'HttpClient' => [ qw( post get ) ];

if ( is_HttpClient( $object ) ) {
  ...;
}
```
