### ISSUE TITLE
`use Type::Library -declare` without `-base` should result in an error

### ISSUE THREAD

**Issue by djerius** [tobyink/p5-type-tiny#119]
Howdy,
Tested under 1.999006, 1.016000

The following code:
```
package My::Types;

use strict;
use warnings;

use Type::Library -declare => 'ucdType';
use Types::Standard  qw( Any );

use Type::Utils -all;

declare ucdType,
  as Any;
```
results in the mysterious error:
```
Can't locate object method "get_type" via package "My::Types" at lib/Type/Library.pm line 142.
```
Passing the type to `declare` as a string rather than the predeclared type reveals the error:
```
"ucdType" is not a valid type name at dev/types_error.pm line 11.
```

**Comment by djerius** [comment]
User error. forgot '-base'. Please disregard.

**Comment by tobyink** [comment]
Hmm, still an interesting case.

I guess `-declare` without `-base`/`-extends` should result in an error.

**Comment by djerius** [comment]
Bit of a head-scratcher. Reused some code which used `-extends`, removed the `-extends` having forgotten that it implicitly provides `-base`, and boom.

**Comment by tobyink** [comment]
1.999_008 should include a fix for this

**Comment by djerius** [comment]
Thanks!
