### ISSUE TITLE
Types::XSD::Lite fails tests under type::Tiny-2.000000

### ISSUE THREAD

**Issue by djerius** [tobyink/p5-type-tiny#122]
When running `t/03anchored.t` one gets this:

Can't locate object method "_mksub" via package "Types::XSD::Lite" at [...]/Types-XSD-Lite-0.006/blib/lib/Types/XSD/Lite.pm line 341.

See e.g., 
http://www.cpantesters.org/cpan/report/276cbfb8-3d2c-11ed-b518-699732644bc0

I get the same error under 5.10, so it doesn't seem to be Perl version specific.

**Comment by tobyink** [comment]
Thanks. Types::XSD::Lite relied too much on undocumented Type::Tiny internals for implementing facets. I've rewritten it to (I think) only rely on the documented API.

**Comment by djerius** [comment]
Thanks!
