### ISSUE TITLE
"Use of uninitialized value $_" message from Union

### ISSUE THREAD

**Issue by djerius** [tobyink/p5-type-tiny#123]
Perl 5.36:

Old:
$ perl -MTypes::Standard=-all -E 'say Type::Tiny->VERSION; Enum( ["internal"] ) | Undef'
1.016010

New:
$ perl -MTypes::Standard=-all -E 'say Type::Tiny->VERSION; Enum( ["internal"] ) | Undef'
2.000000
Use of uninitialized value $_ in string ne at /home/dj/tmp/5.36/lib/perl5/Type/Tiny/Union.pm line 33.

**Comment by tobyink** [comment]
Fixed in 2.000001

**Comment by djerius** [comment]
Thanks!
