### ISSUE TITLE
[RFE] Option for Enum type to match case-insensitively and coerce values

### ISSUE THREAD

**Issue by robrwo** [tobyink/p5-type-tiny#124]
It would be useful to allow the Enum[] type to match values case-insensitively and to coerce values.  (Coercion is probably easier if they are all upper or lower case, it might make it a bit more complicated for mixed case though.)

**Comment by tobyink** [comment]
This should already work...

```perl
use v5.20;

package FirstTest {
	use Types::Standard qw(Enum);
	# The \1 is an indicator that you want coercions
	my $enum = Enum[ \1, qw( foo bar baz ) ];
	say $enum->coerce("Fo");
	say $enum->coerce(1);
}

package SecondTest {
	use Type::Tiny::Enum Thingy => [ qw(foo bar baz) ];
	say Thingy->coerce("baZ");
}
```

**Comment by robrwo** [comment]
The second test doesn't work for me. I get the following error:
> Can't locate object method "coerce" via package "Thingy" (perhaps you forgot to load "Thingy"?)

Type::Tiny::Enum 1.016009

**Comment by tobyink** [comment]
Yes, Type::Tiny::Enum only became an exporter in v2
