### ISSUE TITLE
parameter type's coercion not fired if  coercion of sub-type of parameterized type is fired.

### ISSUE THREAD

**Issue by djerius** [tobyink/p5-type-tiny#132]
I have a type `Base` with a coercion from a `Str`. I'd like to coerce a comma delimited string of things into an array of that type.

    use v5.10;

    use Types::Standard -all;
    use Data::Dump;

    use constant Base => ArrayRef->plus_coercions( Str, sub { say 'Base'; [$_] } );
    use constant ArrayOfBase => ArrayRef->of( Base )->plus_coercions(
        Str,
        sub {
            say "ArrayOfBase";
            [ split qr/,/ ];
        } );

    dd ArrayOfBase->assert_coerce( [ 4, 6 ] );
    dd ArrayOfBase->assert_coerce( '4,6' )

This results in:

    Base
    Base
    [[4], [6]]
    ArrayOfBase
    Reference [4,6] did not pass type constraint "ArrayRef[ArrayRef]" at - line 15
        "ArrayRef[ArrayRef]" is a subtype of "ArrayRef[ArrayRef]"
        Reference [4,6] did not pass type constraint "ArrayRef[ArrayRef]"
        "ArrayRef[ArrayRef]" constrains each value in the array with "ArrayRef"
        "ArrayRef" is a subtype of "ArrayRef"
        "ArrayRef" is a subtype of "Ref"
        Value "4" did not pass type constraint "Ref" (in $_->[0])
        "Ref" is defined as: (!!ref($_))

So,

    ArrayOfBase->assert_coerce( [4,6] );

correctly fires `Base`'s coercion, while correctly skipping `ArrayOfBase`'s, while

    ArrayOfBase->assert_coerce( '4,6' )

correctly fires `ArrayOfBase`'s coercion, but (unexpectedly, incorrectly?) doesn't fire `Base`'s.

Are my expectations wrong?  Is this a manifestation of "Deep/Chained" coercions being weird?

Thanks,
Diab

**Comment by tobyink** [comment]
This sub:

```perl
sub {
        say "ArrayOfBase";
        [ split qr/,/ ];
    }
```

... is expected to return a value which *actually passes* the `ArrayOfBase` type constraint. It's currently just returning something which *could potentially be coerced* to `ArrayOfBase`.

If you change it to this, you should get your expected behaviour:

```perl
sub {
        say "ArrayOfBase";
        [ map { to_Base $_ } split qr/,/ ];
    }
```

This is covered in the manual, here:

https://typetiny.toby.ink/Coercions.html#Chained_Coercions

**Comment by djerius** [comment]
Thanks. For some reason I was unable to map from the manual onto this. (Which is hilarious, because I think you added that section because of similar confusion on my part a few years back.)

Sorry for the noise!
