### ISSUE TITLE
Call to `tie` does not initialize variable as documented

### ISSUE THREAD

**Issue by m-dango** [tobyink/p5-type-tiny#143]
There are places in the documentation where Perl's `tie` is used to initialize a variable. However, the args given after the type look to be dropped. I'm not sure if this is a documentation error or a bug.

https://replit.com/@m-dango/TypeTiny-tie#main.pl

https://github.com/tobyink/p5-type-tiny/blob/48a4d53e444df42680076db82b9e742e9886cae7/lib/Type/Tiny/Manual/UsingWithMoo2.pod?plain=1#L280

https://github.com/tobyink/p5-type-tiny/blob/48a4d53e444df42680076db82b9e742e9886cae7/lib/Type/Tie.pm#L344

**Comment by tobyink** [comment]
This is a bug. It works when you use Type::Tie's `ttie` wrapper, but not when you directly tie a variable to a type. Should be fixed in the next release.

Further, from the next release, this should work:

```perl
tie my $x, Int;
say $x;   # 0, not undef, because undef isn't an integer!
```
