### ISSUE TITLE
Status of parameterized coercion API?

### ISSUE THREAD

**Issue by djerius** [tobyink/p5-type-tiny#147]
The documentation for `Type::Coercion` warns that the API for `coercion_generator` is unstable, and that it "may change in the near future".  It's been that way for a while; have things settled down to the point that the API can be considered stable?

Thanks,
Diab

**Comment by tobyink** [comment]
Parameterized coercions are a feature that nobody seems to really use. I don't have any real plans to change how they work, but if people start using them and find that the current API has issues or limitations, I want the flexibility to be able to change the API.
