### ISSUE TITLE
empty string expected when tying an undefined variable to a Str type constraint

### ISSUE THREAD

**Issue by XSven** [tobyink/p5-type-tiny#152]
I am expecting both tests to pass. Unfortunately the `empty string` test is failing.

```
use Test::More tests => 2;

use Type::Tie       qw( ttie );
use Types::Standard qw( Num Str );

ttie my @n, Num;
is_deeply \@n, [], 'empty list';

ttie my $s, Str;
is $s, '', 'empty string';
```

From my perspective, a proper initial value ("zero" value in golang terminology) should be assigned to an undefined scalar variable. The value has to honour the type constraint. Maybe Type::Tie::SCALAR::_DEFAULT has to depend on the type constraint.

**Comment by tobyink** [comment]
This will be fixed in the next release.
