### ISSUE TITLE
Type::Tiny failing on CPANtesters; smartmatch is gone

### ISSUE THREAD

**Issue by jkeenan** [tobyink/p5-type-tiny#160]
Type-Tiny has begun to fail its tests on CPANtesters.  See, *e.g.,* http://www.cpantesters.org/cpan/report/f4153eac-5c9a-11ef-ad2f-c31a2252ae11.

Sample failure output:
```
syntax error at t/20-modules/Type-Coercion/smartmatch.t line 40, near "3.1 ~"
Execution of t/20-modules/Type-Coercion/smartmatch.t aborted due to compilation errors.
t/20-modules/Type-Coercion/smartmatch.t ...................... 
Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run 
...
syntax error at t/20-modules/Type-Tiny/smartmatch.t line 37, near "42 ~"
Execution of t/20-modules/Type-Tiny/smartmatch.t aborted due to compilation errors.
t/20-modules/Type-Tiny/smartmatch.t .......................... 
Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run 
```
The smartmatch operator was removed from Perl 5 blead this month.  This will be reflected in the perl-5.41.3 monthly development release currently scheduled for Aug 20 and later in perl-5.42.0.  Since quite a few other CPAN libraries depend on Type-Tiny, they will not be testable or installable in dependency-order contexts.  Hence, it is recommended that you work around the non-availability of smartmatch and issue a new CPAN release at your earliest opportunity.

Thank you very much.

**Comment by karenetheridge** [comment]
Hi, 5.41.3 is now out; could this change please be released?
