### ISSUE TITLE
"Default" type constraint for using with Dict and Tuple

### ISSUE THREAD

**Issue by zdm** [tobyink/p5-type-tiny#18]
Hi.

Maybe it will be useful to add "Default" constraint.

```
Dict [
    aaa => Default [Num, 10],
    bbb => Default [20],
]
```

It should check if key exists, and if exists - validate value type, if type constraint present.
If key not exists - create key with default value.

And the same for Tuple.

**Comment by tobyink** [comment]
I might add defaults to Type::Params at some point. And maybe to Dict/Tuple coercions. But if so, it would probably be:

    Dict[
        aaa => Optional[Num, 10],
        bbb => Optional[Any, 20],
    ];
