### ISSUE TITLE
Inline coerce warnings: `Found = in conditional, should be ==`

### ISSUE THREAD

**Issue by zitsen** [tobyink/p5-type-tiny#24]
I'm using inlined coercions in [Mandel](https://metacpan.org/source/Mandel::Model).

Using Perl 5.18.2 on Ubuntu 14.04, it causes warnings while coercing type `Dict`.

```
Found = in conditional, should be ==
```

This test show the warning:

``` perl
use strict;
use warnings;
use Types::Standard -all;
my $value = { key => 'value' };
my $type = Dict[key => Str];

eval $type->coercion->inline_coercion('$value');
```

I've print out the inlined code, seems the warning caused here:

``` perl
($new{"key"}=$tmp) : ($return_orig=1 and last DICTLABEL1)
```

Till now, I have to disable warnings when eval the inlined code. Would you fix it?

**Comment by robrwo** [comment]
+1

**Comment by tobyink** [comment]
Generally speaking, Type::Tiny does evaluate the code in a sandbox where strict is enabled but warnings are not.
