### ISSUE TITLE
Weird Perl <5.14 error with Union Types

### ISSUE THREAD

**Issue by bluefeet** [tobyink/p5-type-tiny#29]
Travis CI complained to me about all my builds using Perl less than 5.14.  It only happens with a very particular combination of union types.  I've narrowed it down to a unit test:

```
: perl -v
This is perl, v5.10.1 (*) built for darwin-2level
```

```
#!/usr/bin/env perl

use Test::More;
use Test::Fatal;

use Types::Standard -types;

is(
    exception { InstanceOf[ 'Foo::Bar' ] },
    undef,
    'InstanceOf worked',
);

is(
    exception { InstanceOf[ 'Foo::Bar' ] | Str },
    undef,
    'InstanceOf|Str worked',
);

is(
    exception { InstanceOf[ 'Foo::Bar' ] | HashRef },
    undef,
    'InstanceOf|HashRef worked',
);

is(
    exception { InstanceOf[ 'Foo::Bar' ] | HashRef | Str },
    undef,
    'InstanceOf|HashRef|Str worked',
);

done_testing;
```

```
ok 1 - InstanceOf worked
ok 2 - InstanceOf|Str worked
ok 3 - InstanceOf|HashRef worked
not ok 4 - InstanceOf|HashRef|Str worked
#   Failed test 'InstanceOf|HashRef|Str worked'
#   at lib/Starch/Store/DBI.pm line 29.
#          got: 'Can't locate object method "has_coercion" via package "Type::Tiny::_HalfOp" at /Users/aran/perl5/perlbrew/perls/perl-5.10.1/lib/site_perl/5.10.1/Type/Tiny/Union.pm line 55.
# '
#     expected: undef
1..4
# Looks like you failed 1 test of 4.
```

**Comment by bluefeet** [comment]
Note that the error is not produced if I build the type in two steps:

```
my $type = InstanceOf[ 'Foo::Bar' ] | HashRef;
$type = $type | Str;
```

**Comment by bluefeet** [comment]
Seems I can get around this with minimal change, but its really funky:

```
((InstanceOf['Foo::Bar']) | HashRef) | Str;
```

**Comment by preaction** [comment]
This also happened to me with the union `HashRef[ArrayRef[HashRef|Str]|HashRef|Str]` which I fixed by doing `HashRef[(ArrayRef[HashRef|Str]|HashRef)|Str]`.

**Comment by tobyink** [comment]
Hmmm. Interesting. There used to be an issue when it came to this:

    ArrayRef[Int] | Int

Because older Perls would interpret it as:

    ArrayRef(   [Int] | Int   )

@haarg fixed it with the `Type::Tiny::_HalfOp` class, but it seems that the fix is only partial.

**Comment by tobyink** [comment]
Moved to RT.

https://rt.cpan.org/Ticket/Display.html?id=121764
