### ISSUE TITLE
Can't locate object method "history" via package "Test::Builder"

### ISSUE THREAD

**Issue by wbraswell** [tobyink/p5-type-tiny#36]
$ cpanm Type::Tiny
...
t/30-integration/Moose/accept-moose-types.t ............... ok
Name "Moose::Meta::TypeCoercion::dummy_3" used only once: possible typo at t/30-integration/Moose/basic.t line 308.
Name "Moose::Meta::TypeConstraint::dummy_1" used only once: possible typo at t/30-integration/Moose/basic.t line 305.
t/30-integration/Moose/basic.t ............................ ok
t/30-integration/Moose/coercion.t ......................... skipped: Moose version 2.12 required--this is only version 2.1005 at (eval 6) line 1.
t/30-integration/Moose/inflate-then-inline.t .............. ok
Can't locate object method "history" via package "Test::Builder" at /usr/lib/perl5/Test/Moose.pm line 80.
&#35; Tests were run but no plan was declared and done_testing() was not seen.
&#35; Looks like your test exited with 255 just after 1.
t/30-integration/Moose/native-attribute-traits.t .......... 
Dubious, test returned 255 (wstat 65280, 0xff00)
All 1 subtests passed 
t/30-integration/MooseX-Getopt/coercion.t ................. skipped: MooseX::Getopt version 0.63 required--this is only version 0.59 at (eval 238) line 1.
...
Test Summary Report
...
t/30-integration/Moose/native-attribute-traits.t        (Wstat: 65280 Tests: 1 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
Files=151, Tests=1834, 26 wallclock secs ( 0.57 usr  0.24 sys + 20.20 cusr  3.64 csys = 24.65 CPU)
Result: FAIL
Failed 1/151 test programs. 0/1834 subtests failed.
make: *** [test_dynamic] Error 255

$ cat /etc/issue
Ubuntu 14.04.5 LTS

$ perl -v
This is perl 5, version 18, subversion 2 (v5.18.2) built for x86_64-linux-gnu-thread-multi

**Comment by tobyink** [comment]
This appears to be an issue in Test::Moose (part of Moose) older than 2.1210.

I've raised the minimum version of Moose for this test from 2.06 to 2.1210.
