### ISSUE TITLE
FileHandle behaviour is different between Type::Tiny and Type::Tiny::XS

### ISSUE THREAD

**Issue by tsibley** [tobyink/p5-type-tiny#38]
```shell
$ perl -MIO::String -MTypes::Standard=:types -E 'FileHandle->assert_valid( IO::String->new ) and say "OK"'
OK

$ perl -MDevel::Hide=Type::Tiny::XS -MIO::String -MTypes::Standard=:types -E 'FileHandle->assert_valid( IO::String->new ) and say "OK"'
Devel::Hide hides Type/Tiny/XS.pm
Reference bless( \*Symbol::GEN0, 'IO::String' ) did not pass type constraint "FileHandle" at -e line 1
    Reference bless( \*Symbol::GEN0, 'IO::String' ) did not pass type constraint "FileHandle"
    "FileHandle" is defined as: ((ref($_) eq "GLOB" && Scalar::Util::openhandle($_)) or (Scalar::Util::blessed($_) && $_->isa("IO::Handle")))
```

This is with Type::Tiny 1.000005 and Type::Tiny::XS 0.012.

**Comment by tobyink** [comment]
Really the whole question of what is and is not considered a file handle in Perl is a little muddy. Whether IO::String objects should be considered to be file handles could be argued either way. I don't think either behaviour you observe is really *incorrect*, however it would be nice if they were *consistent*.

Do you have a suggested fix?

**Comment by tsibley** [comment]
I think making Types::Standard match the Type::Tiny::XS behaviour (i.e. considering IO::String a FileHandle) is more desirable.

I don't have a patch because I was not quite able to follow the XS function enough to spot the difference between the pure Perl check and the check in C.

**Comment by tsibley** [comment]
To clarify, I do agree it could be argued either way.  As long as it's consistent, that's fine by me.  Personally, I think IO::String should be considered a FileHandle.

**Comment by tobyink** [comment]
Okay, so the current pure Perl check is:

		(ref($_) eq "GLOB" && Scalar::Util::openhandle($_))
		or (blessed($_) && $_->isa("IO::Handle"))

I think it can be made consistent with the XS by changing it to:

		(Scalar::Util::reftype($_) eq "GLOB" && Scalar::Util::openhandle($_))
		or (blessed($_) && $_->isa("IO::Handle"))

Advantages:

* Makes Type::Tiny and Type::Tiny::XS consistent.
* Allows IO::String to pass the type constraint.
* Makes Type::Tiny and Mouse consistent.

Disadvantages:

* Inconsistent with Moose.
* Breaks encapsulation by caring about the reftype of a blessed object.

**Comment by tobyink** [comment]
MooX::Types::MooseLike::Base uses this check:

	(defined($_) && Scalar::Util::openhandle($_))
	or (blessed($_) && $_->isa("IO::Handle"))

That's a fairly nice solution. Doesn't break encapsulation. The following might fail faster in the case of non-references:

	(ref($_) && Scalar::Util::openhandle($_))
	or (blessed($_) && $_->isa("IO::Handle"))

**Comment by tobyink** [comment]
Moved to RT.
https://rt.cpan.org/Ticket/Display.html?id=121762
