### ISSUE TITLE
Types::Standard::StrMatch throws the avoiding callbacks warning

### ISSUE THREAD

**Issue by tobyink** [tobyink/p5-type-tiny#60]
Migrated from [rt.cpan.org #133887](https://rt.cpan.org/Ticket/Display.html?id=133887) (status was 'new')

Requestors:
* jjwright@cpan.org

From jjwright@cpan.org on 2020-12-10 04:36:18
:

This code
use Types::Standard -types; use strict; use warnings; use Type::Utils -all;
#use re 'debug'; local $Type::Tiny::AvoidCallbacks = 0; my $Distance = declare
"Distance" => as StrMatch[ qr{^([0-9]+)\s*(mm|cm|m|km)$} ]; my $x = "5ym"; my
$y = $Distance->($x);
throws (and warns) the following:
Cannot serialize regexp without callbacks; serializing using callbacks at
/home/perl/perl5/perlbrew/perls/perl-5.8.9/lib/site_perl/5.8.9/Type/Tiny.pm
line 853 Value "5ym" did not pass type constraint "Distance" at ./test-1.pl
line 13 "Distance" is a subtype of
"StrMatch[(?-xism:^([0-9]+)\s*(mm|cm|m|km)$)]" Value "5ym" did not pass type
constraint "StrMatch[(?-xism:^([0-9]+)\s*(mm|cm|m|km)$)]"
"StrMatch[(?-xism:^([0-9]+)\s*(mm|cm|m|km)$)]" is defined as: do { package
Type::Tiny; !ref($_) and $_ =~
$Types::Standard::StrMatch::expressions{"Regexp|(?-xism:^([0-9]+)\\s*(mm|cm|m|km)\$)"}
}
on Perl 5.8.9 and 5.30.2 with or without Type::Tiny::XS installed, with or
without AvoidCallbacks set

**Comment by tobyink** [comment]
From jjwright@cpan.org on 2020-12-13 04:27:25
:

On Wed Dec 09 23:36:18 2020, JWRIGHT wrote:
> This code
> use Types::Standard -types; use strict; use warnings; use Type::Utils
> -all;
> #use re 'debug'; local $Type::Tiny::AvoidCallbacks = 0; my $Distance =
> declare
> "Distance" => as StrMatch[ qr{^([0-9]+)\s*(mm|cm|m|km)$} ]; my $x =
> "5ym"; my
> $y = $Distance->($x);
> throws (and warns) the following:
> Cannot serialize regexp without callbacks; serializing using callbacks
> at
> /home/perl/perl5/perlbrew/perls/perl-
> 5.8.9/lib/site_perl/5.8.9/Type/Tiny.pm
> line 853 Value "5ym" did not pass type constraint "Distance" at
> ./test-1.pl
> line 13 "Distance" is a subtype of
> "StrMatch[(?-xism:^([0-9]+)\s*(mm|cm|m|km)$)]" Value "5ym" did not
> pass type
> constraint "StrMatch[(?-xism:^([0-9]+)\s*(mm|cm|m|km)$)]"
> "StrMatch[(?-xism:^([0-9]+)\s*(mm|cm|m|km)$)]" is defined as: do {
> package
> Type::Tiny; !ref($_) and $_ =~
> $Types::Standard::StrMatch::expressions{"Regexp|(?-xism:^([0-
> 9]+)\\s*(mm|cm|m|km)\$)"}
> }
> on Perl 5.8.9 and 5.30.2 with or without Type::Tiny::XS installed,
> with or
> without AvoidCallbacks set
with AvoidCallbacks set to 1, this code throws the warning twice.

the warning is not thrown for ->check or ->validate, but it does appear on
calls to ->validate_explain.
The Type-Tiny pod does claim
"(StrMatch is sometimes unable to, and will issue a warning if it needs to rely
on callbacks when asked not to.)" but in this case, it isn't being asked to not
rely on callbacks

**Comment by tobyink** [comment]
From jjwright@cpan.org on 2020-12-13 04:37:42
:

**Comment by tobyink** [comment]
From jjwright@cpan.org on 2020-12-13 04:38:04
:

**Comment by abeltje** [comment]
Hi,

It looks like this hasn't gone away in version 1.012004. I get [cpan-testers reports](http://matrix.cpantesters.org/?dist=MooX-Params-CompiledValidators%200.04_01) with this problem.
I cannot reproduce on my systems (MacOs, Ubuntu, Win10) and don't know where to start investigating...

Thanks in advance,
-- Abe.

**Comment by abeltje** [comment]
> Hi,
> 
> It looks like this hasn't gone away in version 1.012004. I get [cpan-testers reports](http://matrix.cpantesters.org/?dist=MooX-Params-CompiledValidators%200.04_01) with this problem. I cannot reproduce on my systems (MacOs, Ubuntu, Win10) and don't know where to start investigating...
> 
> Thanks in advance, -- Abe.

As it turns out, installing `Regexp::Util` removes this warning (from my test suite at least). Maybe add a hint in the documentation for this...

Good luck,
-- Abe.

**Comment by tobyink** [comment]
`validate_explain` deliberately sets `$AvoidCallbacks = 1`.

It might be worth having `validate_explain` also catch `$SIG{__WARN__}`.

**Comment by tobyink** [comment]
https://github.com/tobyink/p5-type-tiny/commit/805c98d5c1d2343c134fbe0f989670036096be0a
