### ISSUE TITLE
Code compilation error with localized $"

### ISSUE THREAD

**Issue by bpj** [tobyink/p5-type-tiny#66]
Just FYI I came across a weird bug today — due to my own stupidity more than anything else, but anyways.

I happened to call a function which uses Type::Params::compile for the first time in a scope where I had said `local $" = q{, };` just above because I wanted to print out some arrays as comma separated lists and couldn't be a**ed to do a `join` inbetween. What happened was that compilation of the check function failed because the code suddenly was sprinkled with commas! Lesson learned, but you may want to make sure that `$"` is set to its default value when generating the code. If I was stupid enough to do this then someone else might too. It took me nearly an hour to figure out what was going on...

**Comment by tobyink** [comment]
Do you have a specific signature which fails?

This works, for example:

```
perl -MType::Params=-all -MTypes::Standard=-types -E'local $"=q[,]; my $check = compile(Int,ArrayRef[Int]); $check->(0,[]);'
```

I imagine it's one particular type or combination of types which has a problem.
