### ISSUE TITLE
 support for ( @args, \%options )

### ISSUE THREAD

**Issue by djerius** [tobyink/p5-type-tiny#67]
Howdy,

This may be pie-in-the-sky, but here goes...

There's a common subroutine signature idiom that looks like

`( $arg1, $arg2, ..., $argn, \%opts )`

where the trailing hashref is optional and the number of preceding arguments is variable.  It's typically handled like
```
my $opts = 'HASH' eq ref $_[-1] ? pop : {};
my @args = @_;
```

Or with `Type::Tiny`, maybe something a little unwieldy like this,

    my ( $args, $opts ) = validate (
                                    [ \@_,
                                      'HASH' eq ref $_[-1] ? pop : (),
                                    ],
                                    ArrayRef,
                                    Optional[ Dict[ foo => Any ] ],
                                   );

Instead, something like this would be so much nicer:

`my ( $args, $opts ) = validate( \@_,  slurpyish ArrayRef, Optional[ Dict[ foo => Any ] );`

where when the type parser sees `slurpyish` it skips to the end and works backwards. (I can imagine a universe where if one always scanned backwards, plain old `slurpy` could be used, but I haven't examined all of the corner cases in that universe to know if it really exists.)

Just a thought...

Thanks,
Diab

**Comment by tobyink** [comment]
This seems to work, though I agree it's a little inelegant:

```perl
#!/usr/bin/env perl

use strict;
use warnings;
use feature 'state';

use Types::Standard -types, 'slurpy';
use Type::Params -all;
use Data::Dumper;

sub myfunc {
	state $check = multisig(
		compile( { tail => [ HashRef ] },  slurpy ArrayRef[Int] ),
		compile(                           slurpy ArrayRef[Int] ),
	);
	
	my ( $ints, $opts ) = &$check;
	
	print Dumper( $ints, $opts );
}


myfunc( 1, 2, 3, { foo => 'xyz' } );

myfunc( 1, 2, 3 );
```

**Comment by tobyink** [comment]
Basically a `tail` is a list of extra parameters that appears *after* the main signature, but they are always required, never optional/slurpy.

And `multisig` allows you to combine two signatures, and it will use the first signature that works.

**Comment by djerius** [comment]
I really need to update `Type::Tiny` more often than I do!  I hadn't known about `tail` and `head`.

I do like the concept of using `multisig`, but it seems a bit heavy in this context.  To truly over-engineer things, one could imagine writing a grammar for the possible arguments combinations and having `Type::Tiny` use that to validate the inputs.  But that'd be crazy.  

Thanks!
