### ISSUE TITLE
Possible missing sentences bits in Type::Tiny::Manual::Optimization

### ISSUE THREAD

**Issue by smonff** [tobyink/p5-type-tiny#68]
Hi Toby,

I keep reading your documentation and found some suspicious content in the *Types that can be accelerated* sections of  [Type::Tiny::Manual::Optimization](https://typetiny.toby.ink/Optimization.html) POD: it looks like some sentences bits are missing. 

- line 40 [*The parameterized forms of B\<ArrayRef>, B\<HashRef>, and B\<Map> can be accelerated only if their parameters **are**.*](https://metacpan.org/release/Type-Tiny/source/lib/Type/Tiny/Manual/Optimization.pod#L40)
- line 43 [*The parameterized form of B\<Tuple> can be accelerated if its parameters **are**, [...]*](https://metacpan.org/release/Type-Tiny/source/lib/Type/Tiny/Manual/Optimization.pod#L43)
- line 63 [*L\<Type::Tiny::Union> and L\<Type::Tiny::Intersection> will also be accelerated if their constituent type constraints **are**.*](https://metacpan.org/release/Type-Tiny/source/lib/Type/Tiny/Manual/Optimization.pod#L63)
- line 77 [*The parameterized forms of B\<ArrayRef> and B\<HashRef> can be accelerated only if their parameters **are**.*](https://metacpan.org/release/Type-Tiny/source/lib/Type/Tiny/Manual/Optimization.pod#L77)

I guess they *are "something"*, where *something* would be the missing part? I searched older versions of `Type::Tiny` for something that could have been removed accidentally but couldn't find any more information.

Not 100% sure of what I am reporting here, but I tend to think something is missing: in the case I am wrong, please forgive me and ignore this, then I'll go get some English lesson.

**Comment by rabbiveesh** [comment]
Are should be replaced with 'can', probably

**Comment by tobyink** [comment]
The "something" would be "**accelerated**".

I've asked a question on StackExchange to see what they think...
https://english.stackexchange.com/questions/563328/use-of-x-can-be-y-only-if-z-are

**Comment by smonff** [comment]
I'll go get those English lessons.
