### ISSUE TITLE
Incorrect code example in Type::Utils

### ISSUE THREAD

**Issue by djerius** [tobyink/p5-type-tiny#73]
Howdy.

Type::Utils provides the following example for `inline_as`:
```
declare EvenInt,
   as Int,
   where { $_ % 2 == 0 },
   inline_as {
      return (undef, "($_ % 2 == 0)");
   };
```

There are a couple of problems; 

1. The code that is returned is in double quotes, which prematurely interpolates `$_`
2. It seems that the value is actually available as `$_[0]`, not `$_`

To wit running
```
use 5.10.0;
use Type::Utils -all;
use Types::Standard -types;
use Type::Library -base, -declare => qw( GoodEvenInt BadEvenInt  );

declare BadEvenInt,
    as Int,
    where { $_ % 2 == 0 },
    inline_as {
       return (undef, '($_ % 2 == 0)')
    }
    ;

declare GoodEvenInt,
    as Int,
    where { $_ % 2 == 0 },
    inline_as {
       return (undef, '($_[0] % 2 == 0)')
    }
    ;

say 'Bad';
say "2: ", BadEvenInt->validate( 2 );
say "3: ", BadEvenInt->validate( 3 );

say 'Good';
say "2: ", GoodEvenInt->validate( 2 );
say "3: ", GoodEvenInt->validate( 3 );
```
produces

```
Bad
2:
3:
Good
2:
3: Value "3" did not pass type constraint "GoodEvenInt"
```

**Comment by djerius** [comment]
And even 
> `($_[0] % 2 == 0)`

is incorrect, as if inlined code is combined with another type, it's not `$_[0]` at all. Something like this:
```
declare EvenInt,
    as Int,
    where { $_ % 2 == 0 },
    inline_as {
        my ( undef, $varname ) = @_;
       return (undef, "($varname % 2 == 0)")
    }
    ;
```

**Comment by tobyink** [comment]
I think you'll find `$_` should work as shown.

```perl
use strict;
use warnings;
use Types::Standard -types;
use Type::Utils -all;

my $EvenInt =
   declare as Int,
   where { $_ % 2 == 0 },
   inline_as {
      return (undef, "($_ % 2 == 0)");
   };

print $EvenInt->inline_check('$thing'), "\n";
```

**Comment by tobyink** [comment]
If you want to know how it works, read the source code for the `inline_check` method of Type::Tiny and pay attention to the `local $_` part.

**Comment by djerius** [comment]
> I think you'll find `$_` should work as shown.

I have literally been going around in circles with this, and of course you're correct and it works.  I have no idea how I managed to get it not to work, nor how my tests failed to show this version working.

Sorry for the noise.

**Comment by djerius** [comment]
> If you want to know how it works, read the source code for the `inline_check` method of Type::Tiny and pay attention to the `local $_` part.

Thanks.  I usually read the code, but this time decided not to.  Bad decision!
