### ISSUE TITLE
Bundled types error messages

### ISSUE THREAD

**Issue by brtastic** [tobyink/p5-type-tiny#75]
Hello! I'm using Type::Tiny to write a library that validates input data. So far, it's working very well.

I'm a bit puzzled why Types::Standard does not have detailed error messages specified. They seem to report an error in format that looks more or less like `value "value" did not pass the type constraint "Type"`. Types::Common::Numeric and Types::Common::String have their error messages declared nicely, like `Must be a positive integer` for PositiveInt.

I never expected Type::Tiny error messages to be suitable for end users of my library to see, and I created a mechanism that allows for overriding the error messages, but it would be nice for them to at least have the same format across the type libraries shipped with Type::Tiny. Unless someone wants to internationalize the messages, the error message of PositiveInt or other Types::Common::* types is perfectly fine, but other types bundled in the distribution are a bit surprising with their error format.

**Comment by tobyink** [comment]
Moose's built-in types don't have custom error messages either, but MooseX::Types::Common::String and MooseX::Types::Common::Numeric do. So I basically just did the same thing.

**Comment by brtastic** [comment]
Okay, that makes sense. So just to understand a bit better, is keeping the same error messages as types in Moose a must? Are the current error messages basically set in stone right now, or is there room to improve them (unify their format) in the base library?

I can of course create my own type library, which I'll likely do anyway, but just want to explore the options.

**Comment by tobyink** [comment]
It's possible there are people out there with test cases like:

```perl
use strict;
use warnings;
use Test::More;
use Test::Fatal;

use My::Person;

my $e = exception { My::Person->new( name => undef ) };
like( $e, qr/Undef did not pass type constraint/, 'Cannot create person with no name' );
```

And changing them unnecessarily could break people's test cases.

**Comment by brtastic** [comment]
Yeah, that's understandable. I'll create a type library to fix that for my case, so not a big deal. Thanks anyway!
