### ISSUE TITLE
Please add validation_options supporting on_fail callback

### ISSUE THREAD

**Issue by jsf116** [tobyink/p5-type-tiny#77]
Trying to migrate from **Params::Validate** towards **Type::Params** our team detected an issue regarding the logging.
In the past having in a module using **Params::Validate** the following snippet making use of the function **validation_options**
```
use Log::Any         qw($logger);
use Params::Validate qw(:types validation_options validate_pos);
...
validation_options(
  on_fail => sub {
    local *__ANON__ = (caller(1))[3];
    die($logger->fatal($_[0]));
  }
);
```
we have been able to easily log each error message raised during the validation and then to propagate the corresponding exception.
Reading the documentation of **Type::Params** we have not found any adequate replacement for this very useful functionality.
And, of course, we would not like to additionally catch exceptions from functions / methods using **Type::Params** wherever they are called - both because this would significantly increase the effort and due to annoying and dangerous redundancy caused by such approach.

As far as I see, all validation exceptions are thrown by **Error::TypeTiny**, which, in turn, is used by **Type::Params** so that the question is, whether the **throw** method in this module could be expanded by an additional (optional?) named parameter e.g. **redirection**? If omitted, **throw** works as before, if contains a coderef - which can be set by calling of **validation_options**, then **throw** calls at the end this function instead of the currently used **die**.

Thanks and Regards,
jsf

**Comment by tobyink** [comment]
Wouldn't it make more sense to use `$SIG{__DIE__}` to log any exceptions? This would catch not only exceptions thrown by Type::Params, but also other exceptions that might come up like file errors, network errors, etc.

**Comment by jsf116** [comment]
The `$SIG{__DIE__}` approach is in many cases suitable, but there are two catches (well, they might be considered as two aspects of one and the same problem):

1. This is too global relating to the application.
If `$SIG{__DIE__}` is reset by some other module afterwards, the application behavior will no longer fit the expectations.
Worse still, it is unclear at which time point this will happen and which behavior is currently active.
2. This is too global relating to threads.
Signals are in general not thread-safe and even though threads are officially discouraged in the recent Perl versions, we run some crucial multi-threading daemons developed in Perl and would like to improve them in a manner considering costs i.e. without being forced to provide a really radical step replacing threads with processes.

**Comment by tobyink** [comment]
https://github.com/tobyink/p5-type-tiny/commit/1fbc5fe42ded6b10eba89e1b7d547eeba3afd6a4
