### ISSUE TITLE
type for a role name, that is not instantiated?

### ISSUE THREAD

**Issue by karenetheridge** [tobyink/p5-type-tiny#79]
`ConsumerOf[a]` requires that `a` is an instantiated object. Is there no type constraint for `ClassName->where(sub { $_->DOES($role_name) })` ?

**Comment by tobyink** [comment]
https://metacpan.org/pod/Types::LoadableClass has `ClassDoes`.

**Comment by karenetheridge** [comment]
aha, thanks!
