### ISSUE TITLE
Compiled assertion (maybe _overload_coderef?))

### ISSUE THREAD

**Issue by bpj** [tobyink/p5-type-tiny#82]
I was looking for a compiled assertion to use as a callback with Getopt::Long::Descriptive and after a bit of code diving I discovered that the coderef returned by `_overload_coderef` seems to fit the bill. Would there be any problem with using it as such, and if not maybe an alias `compiled_assertion` would be a good idea?

**Comment by tobyink** [comment]
Yes, it will work. But I wouldn't use:

    my $callback = $type->_overload_coderef;

Instead do:

    my $callback = \&$type;

**Comment by bpj** [comment]
> `my $callback = \&$type;`

Ack, I should have realized that that works! Thanks!
