### ISSUE TITLE
InstanceOf["Foo"] cannot be dereferenced

### ISSUE THREAD

**Issue by karenetheridge** [tobyink/p5-type-tiny#84]
```
$ perl -MPath::Tiny -MTypes::Standard=InstanceOf -wle'InstanceOf["Path::Tiny"]->where(q{not $_->is_dir})'

Can't call method "where" on unblessed reference at -e line 1.
```

**Comment by tobyink** [comment]
That's just how Perl parses it. It sees it as:

```
InstanceOf(
  [
    "Path::Tiny"
  ]->where( q{not $_->is_dir} )
)
```

So, trying to call a method on an arrayref.

Solutions:

* `InstanceOf(["Path::Tiny"])->where(q{not $_->is_dir})`
* `(InstanceOf["Path::Tiny"])->where(q{not $_->is_dir})`
* `InstanceOf->of( "Path::Tiny" )->where( q{not $_->is_dir} )`

The third one is my preferred approach personally.

**Comment by karenetheridge** [comment]
doh of course, thanks :)
