### ISSUE TITLE
InstanceOf["Type"] is not an object

### ISSUE THREAD

**Issue by mbethke** [tobyink/p5-type-tiny#86]
I seem to remember this used to work, but either I have a brainworm or there's a bug. I would expect the second block of tests to work just the same as the first one, but `InstanceOf['Path::Tiny']->check` dies with `Can't call method "check" on unblessed reference`:
```perl
use 5.024;
use warnings;
use Test::More;
use Test::Fatal;
use Path::Tiny;     # just to be sure it's not a missing package, should probably work without
use Types::Standard qw( Str InstanceOf );

is( exception { Str->check("x") }, undef, "Str->check lives");
ok( Str->check("x"), "Str->check succeeds");

is( exception { InstanceOf['Path::Tiny']->check("x") }, undef, "InstanceOf['Path::Tiny']->check lives");
ok( ! InstanceOf['Path::Tiny']->check("x"), "InstanceOf['Path::Tiny']->check fails");
```
Using perl 5.32.1 and Types::Standard 1.012004

**Comment by tobyink** [comment]
Perl parses `InstanceOf['Path::Tiny']->check` as:

```perl
InstanceOf(
  [ 'Path::Tiny' ]->check( "x" )
)
```

So you're calling a method on an unblessed arrayref.

Try one of these instead:

* `InstanceOf( ['Path::Tiny'] )->check( "x" )`
* `( InstanceOf['Path::Tiny'] )->check( "x" )`
* `InstanceOf->of( 'Path::Tiny' )->check( "x" )`
