### ISSUE TITLE
version 1.016002 breaks Catalyst-Runtime

### ISSUE THREAD

**Issue by haarg** [tobyink/p5-type-tiny#92]
The changes to slurpy in 1.016002 have broken Catalyst-Runtime's handling of type constrained dispatch when using a slurpy option. Catalyst was abusing the format of the slurpy option internals to decide how many arguments should be consumed.

I have created a fix for this (https://github.com/perl-catalyst/catalyst-runtime/commit/c2af9db8c99907232e9572dd7de772dce53f03d5) which I should be releasing soon. The new code feels a bit more robust, although looking at the original parameters of a type feels a bit ugly.

I'm not sure if there's really anything for Type::Tiny to do here. I figured you would like to be aware as Catalyst is a higher profile module.

**Comment by tobyink** [comment]
Hmm, I guess adding `$type->{slurpy} = 1` to Slurpy type constraints would let it work with current versions of Catalyst.

**Comment by tobyink** [comment]
1.016002 is now scheduled for deletion on PAUSE. All releases since it have included the above workaround.
